# Site settings
title: DS4PS
email: 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/ds4ps_dev_site" # the subpath of your site, e.g. /blog/
url: "http://ds4ps.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: lecy

header:
  - title: Careers
    url : /careers
  - title: Resources
    url : /resources   
  - title: Data
    url : /data
  - title: Community
    url : /discuss 
    
# Build settings
# markdown: redcarpet
# markdown_ext:  markdown,mkdown,mkdn,mkd,md

# redcarpet:
#   extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
