# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Intro to Data Science
description:        Website for the MS in Program Eval and Data Analytics Program, ASU

# Site subpath, e.g. /blog
baseurl:            "/"

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url :               "https://ds4ps.github.io"

# Site logo, image or text
brand:
    image:          # logo.svg  # e.g. logo.png, upload logo image file to /assets/img/ folder
    text:           Intro to Data Science      # if the above "logo:" image variable  is not set, this text logo is displayed instead

# Default author settings
author:
    name:       Jesse Lecy
    github:     lecy   # Github username for avatar


github_info:
    username:          ds4ps # Github location of the course
    branch:            master
    website-repo:      course-template
    course-repo:       Data-Science-Class

index:
    title: Intro to Data Science for the Social Sector
    image: imac.svg
    subtitle: This course introduces students to the field of data science and its applications in the public sector. Modern performance management and evaluation processes require strong data literacy and the ability to combine and analyze data from a variety of sources to inform managerial processes. We offer a practical, tools-based approach that is designed to build strong foundations for people that want to work as policy analysts or data-driven managers. We will cover data programming fundamentals, visualization, text analysis, automated reporting, and dynamic reporting using dashboards. The course is analytically rigorous, but no prior programming experience is assumed.
    


header:
- title: Syllabus
  url: /
  
- title: Course Schedule
  url: schedule/

- title: Textbook
  url: https://ds4ps.github.io/Data-Science-Class/TEXTBOOK/docs/index.html 

- title: Datasets
  url: datasets/

- title: Resources
  url: resources/

- title: Get Help
  url: discussions/


footer:
- title: Home
  url: /

- title: Datasets
  url: /datasets/

- title: Textbook
  url:  https://bookdown.org/yihui/bookdown-demo/

- title: Course Schedule
  url: /schedule/

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    jesse:
        name:       Jesse Lecy
        github:     lecy    # Github username for avatar

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/asupublicservice
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/asupublicservice/
    linkedin:       https://www.linkedin.com/school/asupublicservice/
    pinterest:
    twitter:        https://twitter.com/asupublicsvc
    vimeo:          
    youtube:        https://www.youtube.com/user/coppvideos

# Twitter share button
twitter_username:

# Default footer image settings
footer:
    copyright:      Made by a <a href="https://www.youtube.com/watch?v=WUAcN9UCnbU">human</a> somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:   UA-123960540-1

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Number of posts displayed on blog page
paginate: 10

# Blog path
paginate_path:      "/news/:num/"

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/

post_css: /assets/css/posts

# Build settings
markdown:           kramdown
highlighter:        rouge

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output: true


markdown: kramdown
kramdown:
  parse_block_html: true



course_url: "https://ds4ps.github.io/Data-Science-Class/"

